---
- name: Destroying TiDB container
  docker_container:
    name: "tidb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Destroying TiKV container
  docker_container:
    name: "tidbkv{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Destroying PD container
  docker_container:
    name: "tidbpd{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Remove volumes
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/etc/localtime:/etc/localtime:ro"
    - "/data:/data"
