---
- name: Destroying TiDB container
  docker_container:
    name: "tidb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Destroying TiKV container
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Destroying TiKV (1) container
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}-1"
    state: absent
    force_kill: yes

- name: Destroying TiKV (2) container
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}-2"
    state: absent
    force_kill: yes

- name: Destroying TiKV (3) container
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}-3"
    state: absent
    force_kill: yes

- name: Destroying PD container
  docker_container:
    name: "tidb-pd-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Remove volumes
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/data:/data"
    - "/opt/local/etc/tidb/conf.d"
