---
- name: Destroying TiDB container
  docker_container:
    name: "tidb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Destroying TiKV container
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes


- name: Destroying TiKV containers
  docker_container:
    name: "tidb-kv-{{ inventory_hostname_short }}-{{ item }}"
    state: absent
    force_kill: yes
  loop:
    - 20161
    - 20162
    - 20163
    - 20164
    - 20165
    - 20166
    - 20167
    - 20168
    - 20169
    - 20170
    - 20171

- name: Destroying PD container
  docker_container:
    name: "tidb-pd-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Remove volumes
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/data:/data"
    - "/opt/local/etc/tidb/conf.d"
