---
- name: Common configuration
  hosts: all
  roles:
    - { role: common,
        tags: common }

- name: Install registry
  hosts: all
  roles :
    - { role: registry,
        tags: registry }

- name: Apply role chrony
  hosts: all
  roles:
    - { role: chrony,
        tags: chrony }

- name: Deploy influxdb
  hosts: control
  roles:
    - { role: influxdb,
        tags: influxdb,
        when: enable_monitoring | bool }

- name: Deploy the grafana
  hosts: control
  roles:
    - { role: grafana,
        tags: grafana,
        when: enable_monitoring | bool }

- name: CockroachDB master deployment
  hosts:
    - database
  roles:
    - { role: cockroachdb,
        tags: cockroachdb,
        when: db == "cockroachdb" }

- name: MariaDB master deployment
  hosts:
    - database
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: db == "mariadb" }

- name: TiDB master deployment
  hosts:
    - database
  roles:
    - { role: tidb,
        tags: tidb,
        when: db == "tidb" }

- name: Install monitoring agents
  hosts:
    - database
  roles:
    - { role: cadvisor,
        tags: cadvisor,
        when: enable_monitoring | bool  }
    - { role: collectd,
        tags: collectd,
        when: (db == "mariadb") and (enable_monitoring | bool) }
